# Generated by Django 3.2.13 on 2025-08-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0027_auto_20230725_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('cycle', models.IntegerField()),
                ('max_ht', models.FloatField()),
                ('l_ini', models.IntegerField()),
                ('l_dev', models.IntegerField()),
                ('l_mid', models.IntegerField()),
                ('l_late', models.IntegerField()),
                ('kc_ini', models.FloatField()),
                ('kc_mid', models.FloatField()),
                ('kc_end', models.FloatField()),
            ],
            options={
                'unique_together': {('name', 'cycle')},
            },
        ),
    ]
