# Generated by Django 3.2.13 on 2025-04-02 09:32

from django.db import migrations, models
import django.db.models.deletion
import wx.models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0032_auto_20241105_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombineDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('initial_date', models.DateTimeField(blank=True, null=True)),
                ('final_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='Raw data', max_length=30)),
                ('lines', models.IntegerField(blank=True, default=None, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=256, null=True)),
                ('stations_ids', models.TextField()),
                ('variable_ids', models.TextField(blank=True, null=True)),
                ('aggregation', models.CharField(default='N/A', max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocalWisCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_wis2_ip_address', models.CharField(max_length=255)),
                ('local_wis2_port', models.IntegerField()),
                ('local_wis2_username', models.CharField(max_length=255)),
                ('local_wis2_password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionalWisCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_wis2_ip_address', models.CharField(max_length=255)),
                ('regional_wis2_port', models.IntegerField()),
                ('regional_wis2_username', models.CharField(max_length=255)),
                ('regional_wis2_password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wis2BoxPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing', models.BooleanField(default=False)),
                ('publish_success', models.IntegerField(default=0)),
                ('publish_fail', models.IntegerField(default=0)),
                ('local_wis2', models.BooleanField(default=False)),
                ('regional_wis2', models.BooleanField(default=False)),
                ('transition', models.BooleanField(default=False)),
                ('add_gts', models.BooleanField(default=False)),
                ('base_aws', models.BooleanField(default=True)),
                ('transit_aws', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wis2PublishOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=256)),
                ('cron_schedule', models.CharField(default='5 * * * *', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='international_exchange',
            field=models.BooleanField(default=False, verbose_name='Enable Publishing to WIS2'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active Station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_automatic',
            field=models.BooleanField(default=True, verbose_name='Automatic Station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_synoptic',
            field=models.BooleanField(default=False, verbose_name='Synoptic Station'),
        ),
        migrations.CreateModel(
            name='Wis2BoxPublishLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('success_log', models.BooleanField()),
                ('log', models.TextField()),
                ('wis2message_exist', models.BooleanField()),
                ('wis2message', models.TextField(default='')),
                ('publish_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.wis2boxpublish')),
            ],
        ),
        migrations.AddField(
            model_name='wis2boxpublish',
            name='publishing_offset',
            field=models.ForeignKey(default=wx.models.Wis2BoxPublish.get_default_wis2_publish_offset, on_delete=django.db.models.deletion.DO_NOTHING, to='wx.wis2publishoffset'),
        ),
        migrations.AddField(
            model_name='wis2boxpublish',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_stations', to='wx.station'),
        ),
        migrations.AddField(
            model_name='wis2boxpublish',
            name='transit_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit_stations', to='wx.station'),
        ),
        migrations.CreateModel(
            name='ManualStationDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=1024)),
                ('filepath', models.CharField(max_length=1024)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('stations_list', models.TextField(blank=True)),
                ('month', models.CharField(default='Not Found', max_length=128)),
                ('observation', models.TextField(blank=True, null=True)),
                ('override_data_on_conflict', models.BooleanField(default=False)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wx.stationdatafilestatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
