# Generated by Django 3.2.13 on 2025-04-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0033_auto_20250402_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_automatic',
            field=models.BooleanField(default=False, verbose_name='Automatic Station'),
        ),
    ]
