# Generated by Django 3.2.13 on 2025-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0034_auto_20250408_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='watershed',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
