# Generated by Django 3.2.13 on 2025-04-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0035_alter_station_watershed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wis2boxpublish',
            old_name='transition',
            new_name='hybrid',
        ),
    ]
