# Generated by Django 3.2.13 on 2025-04-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0036_rename_transition_wis2boxpublish_hybrid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wis2boxpublish',
            old_name='transit_aws',
            new_name='hybrid_aws',
        ),
        migrations.RemoveField(
            model_name='wis2boxpublish',
            name='transit_station',
        ),
        migrations.AddField(
            model_name='wis2boxpublish',
            name='hybrid_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hybrid_stations', to='wx.station'),
        ),
    ]
