# Generated by Django 3.2.13 on 2025-05-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0037_auto_20250421_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='countryisocode',
            options={'ordering': ['name']},
        ),
    ]
