# Generated by Django 3.2.13 on 2025-05-14 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0038_auto_20250507_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeregion',
            options={'ordering': ['country'], 'verbose_name': 'administrative region', 'verbose_name_plural': 'administrative regions'},
        ),
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wx.administrativeregion'),
        ),
    ]
