# Generated by Django 3.2.13 on 2025-05-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0039_auto_20250514_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.ForeignKey(default=33, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wx.administrativeregion'),
        ),
    ]
