# Generated by Django 3.2.13 on 2025-05-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0040_alter_station_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxpermission',
            name='permission',
            field=models.CharField(choices=[('full_access', 'Full Access'), ('read', 'Read'), ('write', 'Write'), ('update', 'Update'), ('delete', 'Delete')], max_length=32),
        ),
    ]
