# Generated by Django 3.2.13 on 2025-12-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0028_crop_soil'),
        ('wx', '0041_alter_wxpermission_permission'),
    ]

    operations = [
    ]
