# Generated by Django 3.2.13 on 2025-12-23 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0042_merge_20251215_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.station'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wx.station'),
        ),
    ]
