# Generated by Django 3.2.13 on 2025-12-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0042_merge_20251215_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedatafile',
            name='aqc_checks',
            field=models.BooleanField(null=False, blank=False, default=False),
        ),
        migrations.AddField(
            model_name='combinedatafile',
            name='mqc_checks',
            field=models.BooleanField(null=False, blank=False, default=False),
        ),
        migrations.AddField(
            model_name='datafile',
            name='aqc_checks',
            field=models.BooleanField(null=False, blank=False, default=False),
        ),
        migrations.AddField(
            model_name='datafile',
            name='mqc_checks',
            field=models.BooleanField(null=False, blank=False, default=False),
        ),
    ]
