# Generated by Django 3.2.13 on 2025-12-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0044_equipmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
