# Generated by Django 3.2.13 on 2025-12-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0046_auto_20251223_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(null=True, db_column='model', on_delete=django.db.models.deletion.SET_NULL, to='wx.equipmentmodel'),
        ),
    ]
