# Generated by Django 3.2.13 on 2025-12-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0048_alter_equipment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.equipmentmodel'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wx.equipmentmodel'),
        ),
    ]
