# Generated by Django 3.2.13 on 2025-12-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0049_auto_20251223_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEquipment',
        ),
    ]
