# Generated by Django 3.2.13 on 2025-12-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0051_historicalequipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'ordering': ['name'], 'verbose_name': 'equipment model', 'verbose_name_plural': 'equipment models'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name'], 'verbose_name': 'equipment type', 'verbose_name_plural': 'equipment types'},
        ),
        migrations.AlterModelOptions(
            name='fundingsource',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
    ]
