# Generated by Django 3.2.13 on 2025-12-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0052_auto_20251223_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.equipmentmodel'),
        ),
    ]
