# Generated by Django 3.2.13 on 2025-12-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0053_alter_equipment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='funding_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.fundingsource'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wx.manufacturer'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
