# Generated by Django 3.2.13 on 2026-01-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0054_auto_20251229_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedatafile',
            name='aqc_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='combinedatafile',
            name='mqc_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datafile',
            name='aqc_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datafile',
            name='mqc_checks',
            field=models.BooleanField(default=False),
        ),
    ]
