# Generated by Django 3.2.13 on 2026-01-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wx', '0055_auto_20260119_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxPermissionPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('url_name', models.CharField(max_length=256, unique=True)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WxGroupPageAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx.wxpermissionpages')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wxgrouppageaccess',
            constraint=models.UniqueConstraint(fields=('group', 'page'), name='unique_group_page'),
        ),
    ]
