# Generated by Django 3.2.13 on 2026-01-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0056_auto_20260122_1946'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wxgrouppageaccess',
            constraint=models.CheckConstraint(check=models.Q(('can_write', False), ('can_read', True), _connector='OR'), name='wx_write_requires_read'),
        ),
        migrations.AddConstraint(
            model_name='wxgrouppageaccess',
            constraint=models.CheckConstraint(check=models.Q(('can_delete', False), ('can_read', True), _connector='OR'), name='wx_delete_requires_read'),
        ),
        migrations.AddConstraint(
            model_name='wxgrouppageaccess',
            constraint=models.CheckConstraint(check=models.Q(('can_read', True), ('can_write', True), ('can_delete', True), _connector='OR'), name='wx_at_least_one_permission'),
        ),
    ]
