# Generated by Django 3.2.13 on 2026-01-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0029_crop_name_spanish'),
        ('wx', '0057_auto_20260122_2227'),
    ]

    operations = [
    ]
